doctrine:
    dbal:
        # Configuration de la connexion à la base de données
        driver: 'pdo_mysql'
        server_version: '10.6' # Version de MySQL/MariaDB
        charset: utf8mb4
        default_table_options:
            charset: utf8mb4
            collate: utf8mb4_unicode_ci
        url: '%env(resolve:DATABASE_URL)%'

    orm:
        # Configuration ORM 
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true