security:
    encoders:
        App\Entity\User:
            algorithm: auto

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        main:
            anonymous: lazy
            provider: app_user_provider
            form_login:
                login_path: app_login
                check_path: app_login
                default_target_path: app_homepage # Chemin après connexion réussie
            logout:
                path: app_logout
                target: app_homepage # Chemin après déconnexion
